export const FETCH_REQUEST = "FETCH_REQUEST" 
export const FETCH_FAILURE = "FETCH_FAILURE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SECOND_AUTH_SUCCESS = "SECOND_AUTH_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const RESEND_TOKEN_SUCCESS = "RESEND_TOKEN_SUCCESS";
export const RECOVERY_SUCCESS = "RECOVERY_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const LOGOUT = "LOGOUT";