export const REQUEST = "REQUEST";
export const REQUEST_STOP = "REQUEST_STOP";
export const REQUEST_FAILURE = "REQUEST_FAILURE";

export const GET_DOCUMENT = "GET_DOCUMENT";

export const GET_DOCUMENTS_BY_USER = "GET_DOCUMENTS_BY_USER";

export const GET_DOCUMENTS= "GET_DOCUMENTS";

export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

export const CREATE_DOCUMENT = "CREATE_DOCUMENT";

export const SHARE_DOCUMENT = "SHARE_DOCUMENT";